prefs:
  network.trr.mode: 2
  network.trr.ohttp.config_uri: "https://dooh.cloudflare-dns.com/.well-known/doohconfig"
  network.trr.ohttp.uri: "https://dns.nextdns.io/fc53cb/dns-query"
  network.trr.ohttp.relay_uri: "https://dns.nextdns.io/fc53cb/netw"
  network.trr.use_ohttp: true
